### ISSUE TITLE
Improve - DE using "<" on their form name not rendering

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#236] opened 2017-12-12 11:50 UTC
Questions with the "less than sign (<) are not displaying in Improve module. The lines are blank. 
![improve-blank rows](https://user-images.githubusercontent.com/26415203/33883144-bca0ed6e-df4b-11e7-956c-e39e7d87c90f.jpg)

**Comment by rodmelia** [comment] 2017-12-15 08:01
Server: data.psi-mis.org
User: KEdemo1 / pw: Kenyademo1

**Comment by ifoche** [comment] 2018-02-07 18:58
we've been unable to reproduce this one neither on android.psi-mis.org nor data.psi-mis.org server. We've used < symbol both in question name and in the feedback but we can see the symbol and no problem at all. For the test on data, we've used KEdemo1 user as suggested. Maybe the "show only failed questions" filter was activated and that's why the question was not showing?

**Comment by lindasato** [comment] 2018-02-08 08:38
Hi @ifoche , the "show only failed questions filter" usually collapses the whole line and it should not appear as a blank row. I just remembered that this is an issue that we had reported in the past and it had been fixed. Please see issue number 174 on the closed issues https://github.com/EyeSeeTea/QAApp/issues/174 . I am thinking it may be the same issue. Thanks.

**Comment by ifoche** [comment] 2018-02-08 09:26
Makes sense. Thank you @lindasato! Closing it

**Comment by lindasato** [comment] 2018-02-08 09:35
Hi Ignacio, I just want to clarify that issue #174 was based on a different bb version (54 i think) and issue #236 is based on bb for 1.3

**Comment by ifoche** [comment] 2018-02-08 09:47
Oh, ok. So I change the milestone to 1.3 and re-open it to be checked for the next 1.3 version. Thanks for the clarification

**Comment by ifoche** [comment] 2018-04-17 11:59
Already implemented on 1.3

**Comment by cristinaelle** [comment] 2018-04-18 15:37
@lindasato to check in 1.3.

**Comment by lindasato** [comment] 2018-04-20 12:50
Confirmed, this is now rendering okay in 1.3

**Closed** 2018-04-20 15:33 UTC
Labels: complexity - med (1-5hr), priority - medium, testing, type - maintenance
