### ISSUE TITLE
Vanishing Assessments on build #55

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#172] opened 2017-04-19 14:54 UTC
While testing bb #55, on two occasions assessments vanished. After completing the assessment, I clicked on "Mark as Complete" then clicked on "Go to Feedback". I was able to view the scores for all the sections in the feedback module. But after clicking the back arrow to "return to all assessments", the assessment vanished and was not on the list of assessments in the Improve module. The monitor module did not also reflect that any assessment for that health area had been done this month. This happened for IMCI and Newborn Resuscitation (Not sure if this is useful though). I tried to replicate the error but after repeating the assessments, they did not vanish.

**Comment by ifoche** [comment] 2017-04-26 22:57
Hi @lindasato. Did the survey get uploaded to the server or it completely vanished from both android app and server?

**Comment by lindasato** [comment] 2017-04-27 07:38
Hi @ifoche . The assessments did not get sent to the server. They vanished from the android app before getting sent.

**Comment by ifoche** [comment] 2017-04-27 17:32
Hi @lindasato, we have the suspicion that this can be a problem with queries not ordered by date. With the incorporation of the new system 2.25-compatible, DB queries were not being ordered by date...and that could cause sent surveys not showing the last survey, and so, you thinking that the survey is not really there. To analyse it properly we would need you to export DB and send it to us (using the developer's options in the settings and then clicking on the option for that purpose that appears in the menu. But, the situation in which that we would be in a good position to detect that error would be if you can:
1) Test the app until the problem appears (we will try to replicate on our side too)
2) Once the problem appears (the survey vanishes) just don't create any new survey. Take a screenshot of the sent surveys screen (so we can see what's the last survey appearing there)
3) Activate "developers options" and export us the DB (sending it to me for instance)
4) Send us the screenshot you took indicating which is the program/OU for which you created a survey that is not showing there

This way we would be able to look in the database just in case there's any other existing survey with a creation date later than the one shown in the sent surveys screen

Does it make sense for you? 

Thanks in advance

**Comment by rodmelia** [comment] 2017-04-28 06:49
Hi Linda and HNQIS team

I understand that you would like the new version of HNQIS soon - it will be
important to send the requested database dump asap - this bug is serious
and I don't think we should release to gPlay BEFORE finding a fix.

Unless you (and Ignacio) cannot reproduce this problem, and then we want to
risk issuing the release without a fix.

**Comment by lindasato** [comment] 2017-04-28 06:56
Hi Ignacio and Rodolfo,


I am in the process of doing multiple assessments right now as per Ignacio's instructions below to try and reproduce the problem and I will get back to you ASAP.


Kind regards,

Linda


________________________________

**Comment by lindasato** [comment] 2017-04-28 08:19
@ifoche and @rodmelia . I have done multiple assessments for all the health areas but I have not been able to reproduce this error.

**Comment by rodmelia** [comment] 2017-04-28 09:22
With Linda in copy now.

cristina

Il giorno 28 apr 2017, alle ore 02:49, Rodolfo Melia <rodolfo.melia@gmail.com<mailto:rodolfo.melia@gmail.com>> ha scritto:

Hi Linda and HNQIS team

I understand that you would like the new version of HNQIS soon - it will be important to send the requested database dump asap - this bug is serious and I don't think we should release to gPlay BEFORE finding a fix.

Unless you (and Ignacio) cannot reproduce this problem, and then we want to risk issuing the release without a fix.

On 27 April 2017 at 19:32, Ignacio Foche <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @lindasato<https://github.com/lindasato>, we have the suspicion that this can be a problem with queries not ordered by date. With the incorporation of the new system 2.25-compatible, DB queries were not being ordered by date...and that could cause sent surveys not showing the last survey, and so, you thinking that the survey is not really there. To analyse it properly we would need you to export DB and send it to us (using the developer's options in the settings and then clicking on the option for that purpose that appears in the menu. But, the situation in which that we would be in a good position to detect that error would be if you can:

  1.  Test the app until the problem appears (we will try to replicate on our side too)
  2.  Once the problem appears (the survey vanishes) just don't create any new survey. Take a screenshot of the sent surveys screen (so we can see what's the last survey appearing there)
  3.  Activate "developers options" and export us the DB (sending it to me for instance)
  4.  Send us the screenshot you took indicating which is the program/OU for which you created a survey that is not showing there

This way we would be able to look in the database just in case there's any other existing survey with a creation date later than the one shown in the sent surveys screen

Does it make sense for you?

Thanks in advance

**Comment by ifoche** [comment] 2017-04-28 17:42
Hi all, we're creating a new buddybuild release with everything but this because we cannot replicate it anymore. I'm closing it and tagging it as invalid. In the event that we find it again, we would reopen it

**Comment by lindasato** [comment] 2017-04-29 13:07
Hi Ignacio,
I have been able to replicate the vanishing assessments in Build #56 (server https://data.psi-mis.org). I performed the following assessments on 29th April 2017:
1. KE HNQIS Hypertension - confirmed it was reflecting in the improve module on the list of assessments (see 1st screenshot). I wasn't  connected to the Internet at this point and this assessment was reflecting as not sent (*).
2. Then performed KE HNQIS Tuberculosis
3. Then KE HNQIS Newborn Resuscitation 
On going back to the improve module, KE HNQIS Tuberculosis and KE HNQIS Newborn Resuscitation were missing but KE HNQIS Hypertension was still reflecting. I then clicked on the monitor module, then went back to improve module and this time even KE HNQIS Hypertension done on 29th was also missing from the list of assessments (2nd screenshot). I was connected to the Internet at this point.

Please confirm the attached database is what you wanted me to send you. I will not repeat the above assessments pending confirmation from your end.

Kind regards, 
Linda

________________________________

**Comment by ifoche** [comment] 2017-05-01 10:24
Hi @lindasato. If you could before doing anything else in the app, send me the DB by email (using the export DB utility from the app), that would be perfect for us to analyze it and try to detect where does the problem come from. BTW I've not received the screenshots you mention...could you attach them to this github issue again? Thanks!

**Comment by lindasato** [comment] 2017-05-01 15:53
Hi @ifoche . I have exported the DB directly from the app. I have sent to notifications@github.com and nacho@eyeseetea.com. I am also reattaching the screenshots I took on 29th April here (see description in my earlier comment). Yesterday (30th April, I had done 2 additional assessments but for different health areas- these were reflecting okay). Today I logged out to test a different country and on logging back to Kenya which had vanishing assessments, two of the assessments which I had reported to be missing on the list on 29th are now on the list. These are KE HNQIS Tuberculosis and KE HNQIS Hypertension.  However, KE Newborn resuscitation done on 29th April is still not reflecting on the list of assessments in improve module. The testing credentials are:
Server: https://www.data.psi-mis.org
Username: KEdemo1
PW: Kenyademo1
Please see screenshots attached: 
1st and 2nd were taken on 29th April-see my comments from 29th April for detailed description. 
The 3rd screenshot-taken on 1st May 2017, as I was resending the DB. This shows KE HNQIS Tuberculosis and KE HNQIS Hypertension now on the list, but KE HNQIS Newborn Resuscitation missing.
Please confirm receipt of the DB, thanks.
![1st screenshot 29th april](https://cloud.githubusercontent.com/assets/26415203/25584571/42178bbe-2e9f-11e7-8da2-6d5caa8ce57f.png)
![2nd screenshot 29th april](https://cloud.githubusercontent.com/assets/26415203/25584574/455ec92c-2e9f-11e7-9d04-a68a5c31b117.png)
![3rd screenshot 1st may](https://cloud.githubusercontent.com/assets/26415203/25584577/48572106-2e9f-11e7-9f09-1e032f1f6cd9.png)

**Comment by ifoche** [comment] 2017-05-01 16:38
Hi @lindasato. Thank you, this is very useful. We're tracing the bug. Please do not upload any new survey for KE HNQIS Newborn Resuscitation until we solve the issue. 

Thank you!

**Comment by lindasato** [comment] 2017-05-01 17:31
Hi @ifoche, noted. I will not upload any for the three health areas.

**Comment by ifoche** [comment] 2017-05-01 17:50
Hi again, we've detected the problem in a query to the DB that was grouping surveys incorrectly. All the surveys were there, the 3 of them, but that query was showing the survey from the 28th as the last one, instead of the one from the 29th. And they were not actually disappearing, but they were not being shown on the list if the app encountered any problem while trying to send them (typically on intermittent connexions). When the app detects that problem, it checks each one of the surveys that tried to send in the last send cycle against the server, and until it is not able to check them, they were not being shown. 

So data is not lost (your DB was really useful to detect that), and we've been able to build a fix for this. We'll include it with the fix for the filter issue in a new build.

Thanks @lindasato

**Closed** 2017-09-05 12:43 UTC
Labels: invalid, testing
