### ISSUE TITLE
1.3.6 - Improve Module QoC scores changing to NaN

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#309] opened 2018-10-09 07:21 UTC
We have noticed that after sometime (not sure how much time), some QoC scores are changing to NaN. When completing surveys, this is not an issue as actual scores display. Later, the scores change to NaN and when you open the assessments whose score is NaN, all sections have 0% scores as though they were never assessed. 
![nan scores](https://user-images.githubusercontent.com/26415203/46652872-06489180-cbad-11e8-9213-1ffc2d1b3e4d.jpg)

![nan scores 2](https://user-images.githubusercontent.com/26415203/46656851-a73c4a00-cbb7-11e8-9f74-dadbdd4db140.png)

**Comment by ifoche** [comment] 2018-10-11 09:36
Looks like not a problem of time but a behavior that depends on the surveys previously uploaded. 

When a survey is created locally and only have values for questions that are not scored, the overall score is 0, is seen as 0-scored and when pushed to the server, the overall score is not sent. Then when a user pull that survey from the server, as the survey doesn't have an overall score in it, it's marked as NaN.

So we see 3 different possibilities here, and we would like you to decide which one is better for you:
1) When the survey is 0-scored, we fill in a 0 overall score and send it to the server. That way the survey will show 0 next time a user pulls the data or when he refreshes metadata&data.
2) When the survey is 0-scored it shows NaN also when it's created locally, so coherently NaN would mean that there's no score because no scored question was answered
3) During the pull process, if a survey doesn't contain overall score we calculate it and put a 0 in these situations (this last one would require more processing during the pull, which may affect to the time that the pull process last).

@lidasato, @cristinaelle which option looks better for you?

**Comment by ifoche** [comment] 2018-10-15 08:51
@lindasato you cannot send an empty survey from the app but it looks like there are empty surveys directly filled in in the server. 
Examples:
https://data.psi-mis.org/api/events/xI4dwwKBzrh
https://data.psi-mis.org/api/events/RhruXJMPHDW

BTW for the second screenshot we don't have a DB and the screenshot is taken without the developer options activated, could we have that so we can check if the problem is also the same in that screenshot?

Thanks!

**Comment by lindasato** [comment] 2018-10-15 09:57
@ifoche, the DB has been exported by the user in second screenshot. Please confirm once you see it.

**Comment by ifoche** [comment] 2018-11-05 15:19
After looking into the exported DB more in detail, we still don't have any clue about how those empty events have been generated in the server. The only thing that we're sure about is that they've not been generated in the app because in the DB the user is null, so they've been downloaded from the server. We don't exclude that they may be sent by some other users' app, but definitively not generated in the device that's been exported. Another very plausible explanation would be that a script server side may be generating them and we just download them, producing the NaN problem. 

My question here is...unless we have a way to replicate it...does it make sense to keep dedicating time to it? May someone aware of server scripts have a look to it? @rodmelia what do you think?

**Comment by cristinaelle** [comment] 2018-11-08 04:58
let's drop this - super low priority, not replicable and it hasn't happened in a consistent / regular way.

**Comment by ifoche** [comment] 2018-11-08 07:13
ok, closing the issue

**Closed** 2018-11-08 07:13 UTC
Labels: complexity - med (1-5hr), priority - low, question, ready
