### ISSUE TITLE
clussiana@psi.org | Multilanguage

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#162] opened 2017-03-13 16:04 UTC
Working but some words are still in English for each of the languages, including dialogue boxes.

**Comment by ifoche** [comment] 2017-03-14 16:26
If we turn #161 into a strings revision work, I would treat this one as duplicate of that one. Depending on your answer there, I will close this and change #161 topic

**Comment by ifoche** [comment] 2017-04-06 09:49
Closing this issue as considered already in #170

**Closed** 2017-04-06 09:49 UTC
Labels: duplicate
