### ISSUE TITLE
Improve module, Action Plan: incorrect calculation of dates of next assessment

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#229] opened 2017-11-29 08:53 UTC
Janet is in Malawi for an End-User Training and she has found that the app Incorrectly calculates the dates of the next visit. See sshots attached. It should be: 6 months if above 80%, 4 months if between 50 and 79% and 2 months if below 50%.

Linda reported this issue on #206: just to add that the Plan module is correctly calculating the dates of next assessment, but the Improve module (Action Plan) doesn't report these correctly. 

![screenshot_2017-11-28-14-19-26](https://user-images.githubusercontent.com/12784825/33366286-db441a84-d4fb-11e7-8147-6a00b94065c8.png)
![screenshot_2017-11-28-14-59-39](https://user-images.githubusercontent.com/12784825/33366287-db8d33fe-d4fb-11e7-99a3-e561d9252b60.png)

**Comment by ifoche** [comment] 2017-12-14 10:46
Duplicate of #210

**Comment by cristinaelle** [comment] 2017-12-14 10:53
Don't think it's a duplicate of #210. Shall we reopen this?

**Comment by ifoche** [comment] 2017-12-14 14:55
@cristinaelle I think you're right. I quickly assumed it was a matter of old scoring vs new scoring, but reading more carefully you're completely right. Sorry for the mistake. Do we have a DB for this situation?

**Comment by cristinaelle** [comment] 2017-12-14 16:56
here: [compressedData.zip](https://github.com/EyeSeeTea/QAApp/files/1560108/compressedData.zip)

tks!

**Comment by rodmelia** [comment] 2018-02-19 09:29
See #254 for new issue

**Comment by ifoche** [comment] 2018-02-20 10:28
See my question in #254 about this

**Comment by rodmelia** [comment] 2018-02-23 12:42
This is a duplicate of #254 - closing

**Closed** 2018-02-26 11:28 UTC
Labels: complexity - low (1hr), priority - critical, question, testing, type - maintenance
