### ISSUE TITLE
App pushes dozens of duplicate events

### ISSUE THREAD

**Issue by davidhuser** [EyeSeeTea/QAApp#187] opened 2017-07-11 09:14 UTC
Hi

The HNQIS app sends many duplicate events within seconds to the singapore-dev server - see this Event Report:
https://singapore-dev.psi-mis.org/dhis-web-event-reports/index.html?id=FHSvmwhUlA3

Your user `ifoche` has SuperUser status, hopefully you can log in.

Also, here is the database of a country user:
https://drive.google.com/a/baosystems.com/file/d/0B3FU6Lx45t71b3hvWDZhWXN1MVU/view?usp=sharing

Name: [redacted]
Android version - 5.0.2
Model no: - SM-P555

original request:
The same score for 4 providers and a lot of assessments for these 4 with a difference in the push date of a handful of seconds (Dim Mawi (AMTR175666-01): 25 assessments, Nguint Mg (AMTR175581-03): 51 assessments, Shine Aung (AMTR175581-02): 51 assessments, U Davit (AMTR175666-04): 38 assessments).

**Comment by cristinaelle** [comment] 2017-07-17 14:04
just to comment that this is happening in data data server, KE HNQIS MNH program:

These events are duplicated:
- sKjvUfeHp07 Pushdate: 2017-06-10T18:17:45.730+0300
- vlyhClFeZdQ Pushdate: 2017-06-10T18:16:11.169+0300
- VJHHn1DqcHQ Pushdate: 2017-06-10T18:19:10.760+0300

Can you please confirm there is a functionality in place to avoid HNQIS send duplicated events?

Thanks!

[events - MNH - New Wananchi Maternity And Nursing Home.xlsx](https://github.com/EyeSeeTea/QAApp/files/1152854/events.-.MNH.-.New.Wananchi.Maternity.And.Nursing.Home.xlsx)

**Comment by ifoche** [comment] 2017-07-17 14:19
I'm so sorry for the delay answering to this issue @davidhuser. I'm not being able to access my ifoche user in the server. I will send you a password through an alternative path. Could you please configure that password in my user? Thank you!

**Comment by ifoche** [comment] 2017-07-17 14:33
@cristinaelle Yes, there're some protections to control duplicates. But we need to study more in detail these cases to guess where do they come from. Would you be able to identify a user sending duplicates and ask him to export his DB? That could be very useful to analyze the problem.

**Comment by ifoche** [comment] 2017-07-17 17:44
@davidhuser would it be possible to have the db from Van Hnem Awi_hnqis user? It looks like he's the origin of every duplicate in the event report you submitted.

**Comment by davidhuser** [comment] 2017-07-17 18:08
@ifoche I could have realized that earlier but my assumptions was also that there are more - I requested that, will keep you posted.

**Comment by cristinaelle** [comment] 2017-07-18 12:58
@ifoche @purdych1 @davidhuser 
Someone from our team (Robi) dig into this and realized that one can push a survey more than once from the app. This is possible: just hard press on the survey in Improve Module and once it opens up in Assess module, click the back button and it allows you to mark survey as complete.

![duplicated events - dhis2](https://user-images.githubusercontent.com/12784825/28318009-d7e15eee-6bd1-11e7-8996-8e7bc9055bbd.jpg)
![duplicated events - hnqis app](https://user-images.githubusercontent.com/12784825/28318010-d83a77c2-6bd1-11e7-9932-3f012ccc3bac.png)

**Comment by purdych1** [comment] 2017-07-24 14:08
@davidhuser @ifoche hi guys - is there any further update on this?  The last update I see associated with this issue on the helpdesk is the receipt of the database from the Lal Khan Lam user for Myanmar on July 11.  @davidhuser you indicated you were going to follow up with the Van Hnem Awi_hnqis user to also get their database - any progress/update on that outside the ticket?  Let me know if I need to send a follow-up email to them as well.

Thanks!

**Comment by davidhuser** [comment] 2017-07-25 10:37
@purdych1 just received the database. @ifoche that's the DB for Van Hnem Awi.
Thank you
https://drive.google.com/open?id=0B3FU6Lx45t71UWxRRGxFRG1QT00

**Comment by ifoche** [comment] 2017-07-26 06:40
Thanks @davidhuser, we will analyze it asap.

**Comment by ifoche** [comment] 2017-07-27 08:07
@davidhuser we think we know the origin of the duplicates. This is a well-known duplicates source. The problem is that on that server the "_CreatedOn" control DE is not available for the user (at least the user doesn't have it in its DB). The app depends on that control DE to determine if it has to resend a survey or not when it dies while it was sending, so it can create duplicates. The problem is that the solution is not only to make that control DE available, but the users would need to download the metadata again in order to retrieve the control DE. Maybe you can use the messaging system for that?

**Comment by davidhuser** [comment] 2017-07-27 10:09
Thank you for finding that - I have moved that DE  to the server and added it to the program. I think the issue can be closed, we'll handle the follow-ups on other channels.

**Comment by davidhuser** [comment] 2017-07-27 10:14
One note though: the issue reported [above](https://github.com/EyeSeeTea/QAApp/issues/187#issuecomment-316055650) by Cristina is not related to that issue with _CreatedOn - this DE is present in the program. Wondering if that should be prevented @ifoche ?

**Comment by ifoche** [comment] 2017-07-27 20:23
Hi @davidhuser. Yes I think we should open a new issue for the issue reported by @cristinaelle and close this one

**Comment by ifoche** [comment] 2017-07-28 05:39
I've created #191 for @cristinaelle issue, I guess we can close this ticket?

**Closed** 2017-07-28 10:20 UTC
Labels: in progress
